build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 30

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: false
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected|serialVersionUID)'
